# Redmine runs tests on own continuous integration server.
# http://www.redmine.org/projects/redmine/wiki/Continuous_integration
# You can also run tests on your environment.

shallow_clone: true

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - git --version
  - hg  --version
  - chcp

build: off

test_script:
  - bundle install --without minimagick
  - set SCMS=mercurial
  - set RUN_ON_NOT_OFFICIAL=
  - set RUBY_VER=2.3
  - set BRANCH=trunk
  - gem install %DATABASE_ADAPTER%
  - bundle exec rake config/database.yml
  - bundle install
  - bundle exec rake ci:setup
  - bundle exec rake test

environment:
  global:
    RAILS_ENV: test
    DATABASE_ADAPTER: sqlite3
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
